version: '3'

services:
  db:
    image: postgres
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: bash "startup.sh"
    volumes:
      - .:/code
#    ports:
#      - "8000:8000"
    depends_on:
      - db
